// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaEERyX5PXS48864PvKCS67aHzjpktRKM',
    appId: '1:474224212706:web:d5f4bd0dcfc29506d7fcbb',
    messagingSenderId: '474224212706',
    projectId: 'upishi-smart',
    authDomain: 'upishi-smart.firebaseapp.com',
    storageBucket: 'upishi-smart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8EjPKNFj4H00gwKe_XqoYTkOj1LzstxY',
    appId: '1:474224212706:android:3226f1fe45c8029ad7fcbb',
    messagingSenderId: '474224212706',
    projectId: 'upishi-smart',
    storageBucket: 'upishi-smart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWiXbKXZKwcRjtiu_7D2Pwq0AjlssZlcs',
    appId: '1:474224212706:ios:e43e82d752fa81b2d7fcbb',
    messagingSenderId: '474224212706',
    projectId: 'upishi-smart',
    storageBucket: 'upishi-smart.appspot.com',
    iosClientId: '474224212706-7gijecjkv5n1oggkmp7o4kvthsoh65si.apps.googleusercontent.com',
    iosBundleId: 'com.example.upishiSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWiXbKXZKwcRjtiu_7D2Pwq0AjlssZlcs',
    appId: '1:474224212706:ios:e43e82d752fa81b2d7fcbb',
    messagingSenderId: '474224212706',
    projectId: 'upishi-smart',
    storageBucket: 'upishi-smart.appspot.com',
    iosClientId: '474224212706-7gijecjkv5n1oggkmp7o4kvthsoh65si.apps.googleusercontent.com',
    iosBundleId: 'com.example.upishiSmart',
  );
}
